spring:
  datasource:
    driver-class-name: 'org.h2.Driver'
    url: 'jdbc:h2:mem:teapot_test;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1'
    name: 'teapot_test'
    username: 'admin'

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'test'
    password: 'test'

    properties:
      mail:
        smtp:
          auth: true

          starttls:
            enable: true
            required: true

  jpa:
    show-sql: true
